### ISSUE TITLE
[feat] community 백 연결

### ISSUE THREAD

**Issue by uujeongLee** [solux-gobajago/28th_1_Gabojago_HangangFlow_Front#33]
## ✅ Checklist
- [x] community 한강 카테고리 연결
- [ ] community 좋아요 연결
- [ ] community 게시글 연결

## ✏️ Description
- dashboard 페이지 리팩토링

## 📋 TODO
- [ ] 할 일
