### ISSUE TITLE
[fix] index.js 오류 수정, app.js, community.js 실시간 배경 이미지 

### ISSUE THREAD

**Issue by uujeongLee** [solux-gobajago/28th_1_Gabojago_HangangFlow_Front#34]
## ✅ Checklist
- [x] index.js findDOMNode is deprecated in StrictMode. 오류 수정
- [x] app.js 실시간 배경 이미지 오류 수정
- [x] community 실시간 배경 이미지 오류 수정

## ✏️ Description
- dashboard 페이지 리팩토링

## 📋 TODO
- [ ] 할 일
