### ISSUE TITLE
[feat] community.js / community.css 페이지 추가

### ISSUE THREAD

**Issue by uujeongLee** [solux-gobajago/28th_1_Gabojago_HangangFlow_Front#8]
## ✅ Checklist
- [x] 커뮤니티 페이지 추가
- [x] 커뮤니티 페이지 레이아웃 메인과 통일
- [ ] 커뮤니티 페이지 배경 gmail 템플릿으로 변경

## ✏️ Description
- dashboard 페이지 리팩토링

## 📋 TODO
- [ ] 할 일목은 체크해주세요
- [x] 이슈 제목 작성

## ✏️ Description
- dashboard 페이지 리팩토링

## 📋 TODO
- [ ] 할 일
